###Company Database
CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE DEPTS(DNAME VARCHAR(20),DNO INT PRIMARY KEY,MGRSTRDATE DATE);
CREATE TABLE EMP(SSN INT PRIMARY KEY,FNAME VARCHAR(20),LNAME VARCHAR(20),ADDRESS VARCHAR(20),SEX CHAR(1),SALARY INT,SUPERSSN REFERENCES EMP(SSN) ON DELETE CASCADE,DNO REFERENCES DEPTS(DNO) ON DELETE CASCADE);
ALTER TABLEDEPTS ADD MGRSSN REFERENCES EMP(SSN) ON DELETE SET NULL;
CREATE TABLE DEPLOC(DNO REFERNCES DEPTS(DNO),DLOC VARCHAR(20));
CREATE TABLE PRJ(PNO INT PRIMARY KEY,PNAME VARCHAR(20),PLOC VARCHAR(20),DNO REFERNCES DEPTS(DNO));
CREATE TABLE WORK(SSN REFERENCES EMP(SSN),PNO REFERENCES PRJ(PNO),HOURS NUMBER(2,2));

INSERT INTO DEPTS VALUES();
