###Company Database
CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE DEPTS(DNAME VARCHAR(20),DNO INT PRIMARY KEY,MGRSTRDATE DATE);
CREATE TABLE EMP(SSN INT PRIMARY KEY,FNAME VARCHAR(20),LNAME VARCHAR(20),ADDRESS VARCHAR(20),SEX CHAR(1),SALARY INT,SUPERSSN REFERENCES EMP(SSN) ON DELETE CASCADE,DNO REFERENCES DEPTS(DNO) ON DELETE CASCADE);
ALTER TABLE DEPTS ADD MGRSSN REFERENCES EMP(SSN) ON DELETE SET NULL;
CREATE TABLE DEPLOC(DNO REFERENCES DEPTS(DNO),DLOC VARCHAR(20));
CREATE TABLE PRJ(PNO INT PRIMARY KEY,PNAME VARCHAR(20),PLOC VARCHAR(20),DNO REFERNCES DEPTS(DNO));
CREATE TABLE WORK(SSN REFERENCES EMP(SSN),PNO REFERENCES PRJ(PNO),HOURS INT);

INSERT INTO DEPTS VALUES('&DNAME',&DNO,'&MGRSTRDATE');
INSERT INTO EMP VALUES(&SSN,'&FNAME','&LNAME','&ADDRESS','&SEX',&SALARY,&SUPERSSN,&DNO);
ALTER TABLE DEPTS ADD MGRSSN REFERENCES EMP(SSN) ON DELETE SET NULL;

INSERT INTO DEPLOC VALUES(&DNO,'&DLOC');
INSERT INTO PRJ VALUES(&PNO,'&PNAME','&PLOC',&DNO);
INSERT INTO WORK VALUES(&SSN,&PNO,&HOURS);

 UPDATE DEPTS SET MGRSSN='333' WHERE DNO=1;
 UPDATE DEPTS SET MGRSSN='111' WHERE DNO=2;
 UPDATE DEPTS SET MGRSSN='444' WHERE DNO=3;
 UPDATE DEPTS SET MGRSSN='555' WHERE DNO=4;
 UPDATE DEPTS SET MGRSSN='777' WHERE DNO=5;
