###Airline/Flight Database
CREATE TABLE FLIGHTS(FLNO INT PRIMARY KEY,SOURCE VARCHAR(20),DESTINATION VARCHAR(20),DISTANCE INT,DEPARTTIME VARCHAR(10),ARRIVALTIME VARCHAR(10),PRICE INT);
CREATE TABLE AIRCRAFT(AID INT PRIMARY KEY,ANAME VARCHAR(20),CRUSINGRANGE INT);
CREATE TABLE EMPLOYEES(EID INT PRIMARY KEY,ENAME VARCHAR(20),SALARY INT);
CREATE TABLE CERTIFIED(EID REFERENCES EMPLOYEES(EID),AID REFERENCES AIRCRAFT(AID));

INSERT INTO FLIGHTS VALUES(&FLNO,'&SOURCE','&DESTINATION',&DISTANCE,'&DEPARTTIME','&ARRIVALTIME',&PRICE);
INSERT INTO AIRCRAFT VALUES(&AID,'&ANAME',&CRUSINGRANGE);
INSERT INTO EMPLOYEES VALUES(&EID,'&ENAME',&SALARY);
INSERT INTO CERTIFIFED VALUES(&EID,&AID);
